streamSink:
  fields: user.screen_name, created_at, favorite_count, retweeted_status.user.screen_name
  fieldSeparator: ','
  store:
    paquet:
      pageSizeBytes: 1048576
      rollingIntervalMins: 5
      outputBaseLocation: /tmp/stream
spring.cloud.stream:
  default-binder: kafka
  bindings.input.destination: twitter-stream-01
  kafka.binder.zkNodes: localhost:2181